### ISSUE TITLE
Single view template ignores `hook` transform

### ISSUE THREAD

**Issue by declandewet** [carrot/roots-records#13]
I'm not sure if this is a bug or by design or simply just a result of limitation, although from the order in which these functions are inspected and called in `lib/index.coffee` suggests that this might be a bug.

When both the `hook` method and the single template options are present on a collection passed to `roots-records` (in my case via the `url` option), the `records.<collection>` local is properly transformed as per the `hook`, but the single view template still refers to the old data, as if the `hook` method were never called.

This is problematic because, in my case, I have to reference an API that is not within my control, and that API points to blog posts that are in two separate languages. I'd like to filter out only the language I need. Eventually, I'd like to separate out each language using Roots' environments feature (as I have done in the past on another project using `dynamic-content`).

Following is the extension code - note that `retrieve_models` simply returns a URL to an API endpoint and in this specific case `current_locale` evaluates to `"eng_GB"`. (The other language in question is Swahili).

```coffeescript
records
      pages: 
        url: retrieve_models 'Page'
        template: 'views/_page.jade'
        collection: (pages) ->
          pages
        out: (page) ->
          "/articles/#{page.slug}"
        hook: (pages) ->
          pages = pages.filter (page) ->
            page.language is current_locale
          pages = pages.map (page) ->
            if page.linked_pages?.length
              page.linked_pages = page.linked_pages.map (uuid) ->
                recommended = {}
                for linked_page in pages when linked_page.uuid is uuid
                  recommended.title = linked_page.title
                  recommended.slug  = linked_page.slug
                  break
                recommended
            page
      locales:
        url: retrieve_models 'Localisation'
      categories:
        url : retrieve_models 'Category'
```

Here's a snapshot of the generated views (notice the Swahili mixed in with the English):

![](http://puu.sh/hp0q8/34b34a200c.png)

If I print out `JSON.stringify(records.pages, null, 2)` on the root index view, none of the Swahili `page` items are present, which is the expected behaviour.

**Comment by declandewet** [comment]
I've made a discovery re: this issue. It turns out the `hook` function *is* being applied, but specifically not the `filter` method. That does not work, but the rest does. Seemingly, for now, it is possible to bypass this issue by using the `collection` method for the same purpose.

**Comment by jenius** [comment]
In #23, I removed `collection` and now `hook` applies before the single view compile. This makes things much more straightforward, I think :grinning:
