### ISSUE TITLE
Hook examples unclear (to me)

### ISSUE THREAD

**Issue by smth** [carrot/roots-records#28]
I want to make use of the ability to modify the JSON (from a URL) before calling it in my template, but am struggling with the examples provided.

Existing code:

``` coffee
  records(
    myapi: { url: http://www.path.to/api/01?key },
    anotherapi: { url: http://www.path.to/api/02?key },
  )
```

I have tried a bunch of stuff, all resulting in errors. The closest to the example would be something like:

``` coffee
  records(
    myapi: 
      url: http://www.path.to/api/01?key,
      hook: (url) ->
        url.my.value = 'changed!'
   )
```

or:

``` coffee
  records(
    myapi: 
      url: http://www.path.to/api/01?key,
      hook: (data) ->
        url.my.value = 'changed!'
   )
```

Any pointers appreciated.

**Comment by jescalan** [comment]
I would try returning a copy of your modified data out of that function :+1: 

So like:

``` coffee
hook: (data) ->
  data.value = 'changed!'
  data
```

**Comment by smth** [comment]
Thank you, that works!

Why is that last line required (I don't think I would have figured that out)?

**Comment by jescalan** [comment]
The last line is your return value. You just need to return the data object you want to have in the hook :grin:
