### ISSUE TITLE
Weird issue: folder with single generated views not working on netlify

### ISSUE THREAD

**Issue by pastorryanhayden** [carrot/roots-records#31]
I'm not sure if this is a netlify problem or a roots-records problem but I was hoping someone would have some insight on it.  When I run my site locally, roots-records works fine and I can access my generated pages using links.  When I run compile on netlify - most of the pages work but I can't follow generated links.  When I download the compiled source, The folders (in this case "post" and "sermons") look like exec files.
Any help would be appreciated.
![screen shot 2016-06-09 at 6 25 30 am](https://cloud.githubusercontent.com/assets/4194905/15928437/71770ee6-2e0c-11e6-852a-9fdbbcd27c76.png)

**Comment by jescalan** [comment]
If it's only happening on netlify and not locally, it's probably a netlify issue. I would open up an issue with netlify support 😁
