### ISSUE TITLE
[FEATURE REQUEST] Add single view compiling support to roots-records

### ISSUE THREAD

**Issue by bzerangue** [carrot/roots-records#6]
I would like to serve Roots JSON API data from our custom CMS and be able to create the pages from the pages generated from our API.

This feature would allow me to utilize Roots sort of how you utilize Roots-Wordpress or Roots-Contentful, and allow me to continue to use our CMS for managing the content. 

Thank you so much for your time!!!

**Comment by joshrowley** [comment]
So I'm thinking about the best API here to support this, @bzerangue and I have discussed this a little bit outside of Github, and what we want is a flexible API for generating single page views from some key in the data returned by the JSON.

Based on the current roots-records API, I think something like this would work well:

```coffee
module.exports =
  extensions: [
    records({
      books: {url: 'http://www.google.com/books', template: 'views/_book_single.jade', collection: (data) -> data.response.pages}
    })
  ]
```

The `collection` key takes a function that's passed in the `data`

**Comment by joshrowley** [comment]
Ooops, I hit the submit button too soon, just updated the last comment on this thread.

**Comment by joshrowley** [comment]
cc/ @bzerangue @kylemac @nporteschaikin @jenius

**Comment by bzerangue** [comment]
@joshrowley - Yes! That does. I was looking for it to operate similarly to that of Roots-Contentful or Roots-Wordpress. But this looks like it would be super flexible, and looks like what I would need it to work like. 

```
module.exports =
  extensions: [
    records({
      books: {
        url: 'http://www.google.com/books',
        template: 'views/_book_single.jade',
        collection: (data) -> data.response.pages,
        path: (item) -> "/books/#{item.name}"
      }
    })
  ]
```

**Comment by joshrowley** [comment]
Hey @bzerangue, check out #7 for an implementation of this.

**Comment by bzerangue** [comment]
@joshrowley Wow! Having some difficulty getting it to work. Will try a few more times and will post if I have any questions!

**Comment by joshrowley** [comment]
@bzerangue might be because it hasn't been released on npm yet, @nporteschaikin mind cutting a new release?, you can also try sourcing the module from github

**Comment by nporteschaikin** [comment]
@joshrowley I'm going to implement the tweaks we discussed before I cut a build.  @bzerangue If you'd like to try the feature now, source the module from github.

**Comment by kylemac** [comment]
@bzerangue if you weren't sure how to do that yet, npm makes it pretty easy. 

```js
# package.json
"dependencies": {
    "roots-records": "git://github.com/carrot/roots-records"
  }
```
and then just include it in your `init.coffee` as you normally would
